services:
  python:
    build: ./src/
    command: sh -c "sleep 10s ; python3 ./main.py"
    depends_on:
      - mysql
  mysql:
    build: ./database/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'

    

